export const EN_LOCALE = {
  HOME: "Home",
  SHORTS: "Shorts",
  SUBSCRIPTIONS: "Subscriptions",
  HISTORY: "History",
  PLAYLISTS: "Playlists",
  YOUR_VIDEOS: "Your videos",
  WATCH_LATER: "Watch later",
  LIKED_VIDEOS: "Liked videos",
  SETTINGS: "Settings",
  HELP: "Help",
  ABOUT: "About",
  CONTACT: "Contact",
  PRIVACY: "Privacy",
  TERMS: "Terms",
  COPYRIGHT: "Copyright",
  PRESS: "Press",
  CREATOR_ACADEMY: "Creator Academy",
  ADVERTISE: "Advertise",
  DEVELOPERS: "Developers",
  LEGAL: "Legal",
  POLICY_AND_SAFETY: "Policy & Safety",
  HOW_YOUTUBE_WORKS: "How YouTube works",
  TEST_NEW_FEATURES: "Test new features",
  MUSIC: "Music",
  GAMING: "Gaming",
  NEWS: "News",
  SPORTS: "Sports",
  YOUTUBE_PREMIUM: "YouTube Premium",
  YOUTUBE_MUSIC: "YouTube Music",
  YOUTUBE_STUDIO: "YouTube Studio",
  YOUTUBE_KIDS: "YouTube Kids",
  REPORT_HISTORY: "Report history",
  YOU: "You",
  SUBSCRIBER: "subscriber",
  SUBSCRIBERS: "subscribers",
  VIEWS: "views",
  SHOW_LESS: "Show less",
  SHOW_MORE: "...more",
};
